apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: mastodon
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: mastodon
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: mastodon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: mastodon
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastodon-external-dns
  namespace: mastodon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mastodon-external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=ingress
        - --domain-filter=$(LOCAL_DOMAIN)
        - --provider=google
        - --registry=txt
        - --txt-owner-id=extdns
        env:
        - name: LOCAL_DOMAIN
          valueFrom:
            secretKeyRef:
              name: mastodon
              key: LOCAL_DOMAIN
        
        